### ISSUE TITLE
最新版 Release 设置存在问题

### ISSUE THREAD

**Issue by TakWolf** [Warren2060/ChillBitmap#5]
https://github.com/Warren2060/ChillBitmap/releases/tag/v.2.502

tag = v.2.502 应为 v2.502

[ChillBitmap.zip](https://github.com/Warren2060/ChillBitmap/releases/download/v.2.502/ChillBitmap.zip) 包内缺少许可证

另外 7px (ttf) 和 16px (otf) 格式不一致

**Comment by Warren2060** [comment]
已更新完成。
